"""empty message

Revision ID: 535528b18ad5
Revises: fcc8e384b913
Create Date: 2018-05-25 13:40:19.895400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535528b18ad5'
down_revision = 'fcc8e384b913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_is', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_is'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
